services:
  frontend:
    image: ghcr.io/kiespetch1/frontend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${CURRENT_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=https"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3001"
      - "traefik.docker.network=unischedule-staging_shared-network"
    networks:
      - monitoring
      - shared-network
    env_file:
      - .env.frontend
      - .env

networks:
  shared-network:
    external: true
    name: unischedule-staging_shared-network
  monitoring:
    external: true
    name: unischedule-staging_monitoring